name: Python CI/CD

on: [push, pull_request]

jobs:
  test-and-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Pobieranie kodu
        uses: actions/checkout@v4

      - name: Konfiguracja pythona
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Instalacja bibliotek
        run: 
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Code review (Flake8)
        run: 
          flake8 . --count --select E9,F63,F7,F82 --show-source --statistics

      - name: Uruchamianie testów
        run: pytest

  deploy:
    needs: test-and-lint
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - name: Symulacja wdrożenia
        run: echo "Wdrożenie aplikacji powiodło sie"
  
      
